---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: crypto-tweet-sense
  name: channel-contentmaker
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: channel-contentmaker
  template:
    metadata:
      name: channel-contentmaker
      labels:
        app: channel-contentmaker
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: twitter-exp
          image: ghcr.io/lueurxax/crypto-tweet-sense-channel-contentmaker:main
          imagePullPolicy: Always
          env:
            - name: LOG_LEVEL
              value: trace
            - name: BOT_TOKEN
              value: 5012820190:AAE7noRh3G_mIivRKRkQq3TfM5wh60u_Vpo
            - name: CHAT_GPT_TOKEN
              value: -arnFyJDaITRuVlKn00muT3BlbkFJpmf5HQad88hntVne2hel
            - name: CHAT_ID
              value: "-1001289077992"
            - name: LOG_TO_ECS
              value: "false"
            - name: DATABASEPATH
              value: "/etc/fdb/fdb.cluster"
          volumeMounts:
            - name: db-cluster
              mountPath: /etc/fdb/
      volumes:
        - name: db-cluster
          configMap:
            name: fdb.cluster
      imagePullSecrets:
        - name: regcred